name: extrinsic_calib
root: ~/nav_ws
pre_window: ./container shell

windows:
  - simulator:
      layout: main-vertical
      panes:
        # - ros2 launch ironback_description description.launch.py
        - ros2 launch spot_driver spot_driver.launch.py config_file:=/home/ros/nav_ws/params/spot_driver.yaml
        - ros2 launch azure_kinect_ros_driver driver.launch.py depth_mode:=NFOV_UNBINNED color_resolution:=720P fps:=30
        - ros2 launch spot_velodyne velodyne.launch.py device_ip:=192.168.50.201
        # - ros2 run image_proc rectify_node --ros-args -r image:=/rgb/image_raw -r camera_info:=/rgb/camera_info -r image_rect:=/rgb/image_rect
        - ros2 run tf2_ros static_transform_publisher 0.0 0.0 0.0 0 0 0 1 body sensor_plate_link
        - ros2 run tf2_ros static_transform_publisher 0.23 0 -0.075 4.7124 0 4.7124 1 sensor_plate_link camera_base
        - ros2 run tf2_ros static_transform_publisher 0.4064 0.03 -0.17 4.6600 0 4.7124 1 sensor_plate_link velodyne
        - vnc
        - sleep 10; DISPLAY=:9 rviz2 -d rviz2/navstack.rviz
