name: ptv3
root: ~/dance_ws_pedestrian_tracking

windows:
  - ptv3:
      layout: main-vertical
      panes:
        - 
        - ros2 launch azure_kinect_ros_driver driver.launch.py depth_mode:=NFOV_UNBINNED color_resolution:=720P fps:=30
        - ros2 launch spot_velodyne velodyne.launch.py
        - vnc
        - sleep 10; DISPLAY=:9 rviz2 -d rviz2/navstack.rviz
