/**:
  ros__parameters:
    pointCloudTopic: "/velodyne_points"
    imuTopic: "/mapping/imu"
    odomTopic: "odometry/imu"
    gpsTopic: "odometry/gps"

    lidarFrame: "velodyne"
    baselinkFrame: "base_link"
    odometryFrame: "odom"
    mapFrame: "map"

    useImuHeadingInitialization: false
    useGpsElevation: false
    gpsCovThreshold: 2.0
    poseCovThreshold: 25.0

    savePCD: false
    savePCDDirectory: "/home/ros/nav_ws/maps/lio_sam/raw/"

    sensor: "velodyne"
    N_SCAN: 16
    Horizon_SCAN: 1800
    downsampleRate: 1
    lidarMinRange: 1.0
    lidarMaxRange: 200.0

    imuAccNoise: 0.01
    imuGyrNoise: 0.005
    imuAccBiasN: 0.0002
    imuGyrBiasN: 0.00003
    imuGravity: 9.81
    imuRPYWeight: 0.01

    extrinsicTrans: [0.0, 0.0, 0.0]
    extrinsicRot: [1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]
    extrinsicRPY: [1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]

    edgeThreshold: 1.0
    surfThreshold: 0.1
    edgeFeatureMinValidNum: 10
    surfFeatureMinValidNum: 100

    odometrySurfLeafSize: 0.4
    mappingCornerLeafSize: 0.2
    mappingSurfLeafSize: 0.4

    z_tollerance: 1000.0
    rotation_tollerance: 1000.0

    numberOfCores: 4
    mappingProcessInterval: 0.15

    surroundingkeyframeAddingDistThreshold: 1.0
    surroundingkeyframeAddingAngleThreshold: 0.2
    surroundingKeyframeDensity: 2.0
    surroundingKeyframeSearchRadius: 50.0

    loopClosureEnableFlag: true
    loopClosureFrequency: 1.0
    surroundingKeyframeSize: 50
    historyKeyframeSearchRadius: 15.0
    historyKeyframeSearchTimeDiff: 30.0
    historyKeyframeSearchNum: 25
    historyKeyframeFitnessScore: 0.3

    globalMapVisualizationSearchRadius: 1000.0
    globalMapVisualizationPoseDensity: 10.0
    globalMapVisualizationLeafSize: 1.0
